// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.HolonomicDrive.commands;

import org.usfirst.frc3824.HolonomicDrive.Constants;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousStackTwoTotesContainer extends CommandGroup
{

	public AutonomousStackTwoTotesContainer()
	{
		ChassisTurnAngle chassisTurn0   = new ChassisTurnAngle(  0.0, 0.0);
		ChassisTurnAngle chassisTurnM45 = new ChassisTurnAngle(-45.0, 0.0);

		// lift the tote over the container
		addSequential(new ForkliftMoveToPosition(Constants.FORKLIFT_TOTE2_POSITION, Constants.FORKLIFT_VELOCITY_SETPOINT_LOW));
		
		// drive forward to get the container
		addSequential(new ChassisDriveStraight(Constants.AUTONOMOUS_TOTE_AND_CONTAINER_DRIVE_TIME,
		                                       Constants.AUTONOMOUS_TOTE_AND_CONTAINER_DRIVE_POWER,
		                                       Constants.AUTONOMOUS_TOTE_AND_CONTAINER_DRIVE_ANGLE));
		
		// move container to side
		addSequential(new ChassisDriveAndTurn(1.0, 0.9, -80.0, -50.0));
		
		// back up to release container
		addSequential(new ChassisDriveAndTurn(1.4, -0.9, -80.0, -50.0));
		
        // lower the forklift
		addParallel(new ForkliftMoveToPosition(Constants.FORKLIFT_TOTE1_POSITION, Constants.FORKLIFT_VELOCITY_SETPOINT_HIGH));
		
		// drive to second tote
		addSequential(new ChassisDriveAndTurn(1.0, 0.6, 0.0, 80.0));
		
		// move totes to auto zone
		addSequential(new ChassisDriveAndTurn(2.5, 0.5, 0, 100.0));
		
		// drive forward to get the container
		//addSequential(new ChassisDriveStraight(2.0, 0.6, 45.0));
	
		//addSequential(new ChassisDriveAndTurn(1.0, 0.5, -45.0, 00));
		
//		// goes for second tote
//		addSequential(new ChassisDriveStraight(1.0, 0.5, 45));
//		addSequential(chassisTurn0);
//		addSequential(new ChassisDriveStraight(1.0, 0.5, 0));
//		addSequential(new ForkliftMoveToPosition(Constants.FORKLIFT_TOTEPICKUP_POSITION, Constants.FORKLIFT_VELOCITY_SETPOINT_HIGH));
//		addSequential(new ForkliftMoveToPosition(Constants.FORKLIFT_TOTE0_POSITION, Constants.FORKLIFT_VELOCITY_SETPOINT_HIGH));
//
//		// takes robot and totes to autozone
//		addSequential(new ChassisDriveStraight(2.0, 0.7, 90));
//		addSequential(new ForkliftMoveToPosition(Constants.FORKLIFT_TOTEPICKUP_POSITION, Constants.FORKLIFT_VELOCITY_SETPOINT_HIGH));
//		addSequential(new ChassisDriveStraight(1.0, 0.5, 180));
	}
}
