// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.HolonomicDrive.commands;

import org.usfirst.frc3824.HolonomicDrive.Constants;

import edu.wpi.first.wpilibj.command.CommandGroup;

/*
 *
 */
public class AutonomousMoveContainerAndAlignToLoad extends CommandGroup
{
	public AutonomousMoveContainerAndAlignToLoad()
	{
		ChassisTurnAngle chassisTurn115Left = new ChassisTurnAngle(-115.0, 0.0);

		// reset the gyro
		addSequential(new ResetGyro());
		
		// push container forward out of the way
		addSequential(new ChassisDriveStraight(Constants.AUTONOMOUS_CONTAINER_STORE_TIME, 
		                                       Constants.AUTONOMOUS_CONTAINER_STORE_POWER,
		                                       Constants.AUTONOMOUS_CONTAINER_STORE_ANGLE));
		
		// drive backward releasing the container
		addSequential(new ChassisDriveStraight(Constants.AUTONOMOUS_CONTAINER_BACKUP_TIME, 
		                                       Constants.AUTONOMOUS_CONTAINER_BACKUP_POWER,
		                                       Constants.AUTONOMOUS_CONTAINER_BACKUP_ANGLE));
		
		// turn robot to have the back at the loading station
		addSequential(chassisTurn115Left);
			
		addSequential(new ChassisDriveStraight(Constants.AUTONOMOUS_CONTAINER_STATION_TIME, 
		                                       Constants.AUTONOMOUS_CONTAINER_STATION_POWER,
		                                       Constants.AUTONOMOUS_CONTAINER_STATION_ANGLE));
	}
}
