// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.HolonomicDrive.commands;

import org.usfirst.frc3824.HolonomicDrive.Constants;

import edu.wpi.first.wpilibj.command.CommandGroup;

public class AutonomousGetTwoContainersFromStep extends CommandGroup {
	public AutonomousGetTwoContainersFromStep() {
		//TODO collect from step; mechanism pending

		// backing up
		addSequential(new ChassisDriveStraight(
				Constants.AUTONOMOUS_CONTAINER_DRIVE_TIME,
				Constants.AUTONOMOUS_CONTAINER_DRIVER_POWER,
				Constants.AUTONOMOUS_CONTAINER_DRIVE_REVERSE_DIRECTION));

		// turn to fit container in auto zone
		addSequential(new ChassisTurnAngle(90.0, 0.0));

		// TODO add command to deposit container

		// deposit and get clear from container
		addSequential(new ChassisDriveStraight(1.25,
				Constants.AUTONOMOUS_CONTAINER_DRIVER_POWER,
				Constants.AUTONOMOUS_CONTAINER_DRIVE_REVERSE_DIRECTION));

		// going to turn towards to next container
		addSequential(new ChassisTurnAngle(-90.0, 0.0));

		// Drives towards the step to get next container
		addSequential(new ChassisDriveStraight(
				Constants.AUTONOMOUS_CONTAINER_DRIVE_TIME,
				Constants.AUTONOMOUS_CONTAINER_DRIVER_POWER,
				Constants.AUTONOMOUS_CONTAINER_DRIVE_FORWARD_DIRECTION));

		// TODO add command to retrieve container

		// backing up
		addSequential(new ChassisDriveStraight(
				Constants.AUTONOMOUS_CONTAINER_DRIVE_TIME,
				Constants.AUTONOMOUS_CONTAINER_DRIVER_POWER,
				Constants.AUTONOMOUS_CONTAINER_DRIVE_REVERSE_DIRECTION));

		// turn to fit container in auto zone
		addSequential(new ChassisTurnAngle(90.0, 0.0));

		// TODO add command to deposit container

		// deposit and get clear from container
		addSequential(new ChassisDriveStraight(0.75,
				Constants.AUTONOMOUS_CONTAINER_DRIVER_POWER,
				Constants.AUTONOMOUS_CONTAINER_DRIVE_REVERSE_DIRECTION));

	}
}
