// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.HolonomicDrive.commands;

import org.usfirst.frc3824.HolonomicDrive.Constants;

import edu.wpi.first.wpilibj.command.CommandGroup;

/*
 *
 */
public class AutonomousToteAndContainer extends CommandGroup
{
	public AutonomousToteAndContainer()
	{
		ChassisTurnAngle chassisTurn90  = new ChassisTurnAngle( 90.0, 0.0);		
		ChassisTurnAngle chassisTurnM90 = new ChassisTurnAngle(-90.0, 0.0);
		
		// reset the gyro
		addSequential(new ResetGyro());
		
		// lift the tote over the container
		addSequential(new ForkliftMoveToPosition(Constants.FORKLIFT_TOTE3_POSITION, Constants.FORKLIFT_VELOCITY_SETPOINT_OVERRIDE));
		
		// drive forward to get the container
		addSequential(new ChassisDriveStraight(Constants.AUTONOMOUS_TOTE_AND_CONTAINER_DRIVE_TIME,
		                                       Constants.AUTONOMOUS_TOTE_AND_CONTAINER_DRIVE_POWER,
		                                       Constants.AUTONOMOUS_TOTE_AND_CONTAINER_DRIVE_ANGLE));
		 
//		// turn towards the autozone
//		addSequential(chassisTurn90);
//		
//		// drive straight to autozone
//		addSequential(new ChassisDriveStraight(2.85, 0.5, 0.0));
		
		// drive and turn to keep the container captured
		addSequential(new ChassisDriveAndTurn(2.7, 0.5, 0.0, 90.0));
	
		// turn towards the autozone
		addSequential(chassisTurnM90);
		
		// drive straight to autozone
		addSequential(new ChassisDriveStraight(0.75, -0.5, 0.0));
		
		// lift the tote over the container
		addSequential(new ForkliftMoveToPosition(Constants.FORKLIFT_TOTEPICKUP_POSITION, Constants.FORKLIFT_VELOCITY_SETPOINT_OVERRIDE));
	}
}
