// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.HolonomicDrive.commands;

import org.usfirst.frc3824.HolonomicDrive.Constants;
import org.usfirst.frc3824.HolonomicDrive.Robot;

import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class AutonomousGetRightContainerFromStep extends CommandGroup {
	public AutonomousGetRightContainerFromStep() {
		double gyroValue;
		double relativeAngle;

		// collect from step; mechanism pending

		// backing up
		addSequential(new ChassisDriveStraight(
				Constants.AUTONOMOUS_CONTAINER_DRIVE_TIME,
				Constants.AUTONOMOUS_CONTAINER_DRIVER_POWER,
				Constants.AUTONOMOUS_CONTAINER_DRIVE_REVERSE_DIRECTION));

		gyroValue = Robot.driveTrain.getGyroValue();
		relativeAngle = Robot.driveTrain.getRelativeAngle();
		SmartDashboard.putNumber("Gyro Angle after backup", gyroValue);
		SmartDashboard.putNumber("Relative Angle after backup", relativeAngle);

		// turn to fit container in auto zone
		addSequential(new ChassisTurnAngle(90.0, 0.0));
		gyroValue = Robot.driveTrain.getGyroValue();
		relativeAngle = Robot.driveTrain.getRelativeAngle();
		SmartDashboard.putNumber("Gyro Angle after turn to right", gyroValue);
		SmartDashboard.putNumber("Relative Angle after turn to right",
				relativeAngle);

		// TODO add command to deposit container

		// deposit and get clear from container
		addSequential(new ChassisDriveStraight(0.75,
				Constants.AUTONOMOUS_CONTAINER_DRIVER_POWER,
				Constants.AUTONOMOUS_CONTAINER_DRIVE_REVERSE_DIRECTION));
		gyroValue = Robot.driveTrain.getGyroValue();
		relativeAngle = Robot.driveTrain.getRelativeAngle();
		SmartDashboard.putNumber("Gyro Angle after backup after turn",
				gyroValue);
		SmartDashboard.putNumber("Relative Angle after backup after turn",
				relativeAngle);
	}
}
