// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.HolonomicDrive.commands;

import org.usfirst.frc3824.HolonomicDrive.Constants;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3824.HolonomicDrive.Robot;

/**
 *
 */
public class ForkliftSetPIDs extends Command
{

	public ForkliftSetPIDs()
	{
		// Use requires() here to declare subsystem dependencies
		// eg. requires(chassis);

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	protected void initialize()
	{
		SmartDashboard.putNumber("Velocity P", Constants.FORKLIFT_VELOCITY_P);
		SmartDashboard.putNumber("Velocity I", Constants.FORKLIFT_VELOCITY_I);
		SmartDashboard.putNumber("Velocity D", Constants.FORKLIFT_VELOCITY_D);
		
		SmartDashboard.putNumber("Position P", Constants.FORKLIFT_POSITION_P);
		SmartDashboard.putNumber("Position I", Constants.FORKLIFT_POSITION_I);
		SmartDashboard.putNumber("Position D", Constants.FORKLIFT_POSITION_D);
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute()
	{
		// read the smart dashboard position PID values
		Robot.forklift.setPIDvalues(Constants.FORKLIFT_POSITION_MODE,
		SmartDashboard.getNumber("Position P"),
		SmartDashboard.getNumber("Position I"),
		SmartDashboard.getNumber("Position D"));
		
		// read the smart dashboard velocity PID values
		Robot.forklift.setPIDvalues(Constants.FORKLIFT_POSITION_MODE,
		SmartDashboard.getNumber("Velocity P"),
		SmartDashboard.getNumber("Velocity I"),
		SmartDashboard.getNumber("Velocity D"));
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished()
	{
		return(true);
	}

	// Called once after isFinished returns true
	protected void end()
	{
		
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted()
	{
		
	}
}
