// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.HolonomicDrive.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3824.HolonomicDrive.Constants;
import org.usfirst.frc3824.HolonomicDrive.Robot;

/**
 *
 */
public class SetCaptureArmOffsets extends Command
{

	public SetCaptureArmOffsets()
	{
		// Use requires() here to declare subsystem dependencies
		// eg. requires(chassis);

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

		SmartDashboard.putNumber("Left Capture Offset", Constants.TOTE_CAPTURE_LEFT_ARM_OFFSET);
		SmartDashboard.putNumber("Right Capture Offset", Constants.TOTE_CAPTURE_RIGHT_ARM_OFFSET);
	}

	// Called just before this Command runs the first time
	protected void initialize()
	{
		double right, left;
		
		left  = SmartDashboard.getNumber("Left Capture Offset");
		right = SmartDashboard.getNumber("Right Capture Offset");
	
		Robot.toteCapture.setArmOffsets(right, left);
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute()
	{
		
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished()
	{
		return true;
	}

	// Called once after isFinished returns true
	protected void end()
	{
		
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted()
	{
		
	}
}
