// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3824.HolonomicDrive.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3824.HolonomicDrive.Robot;
import org.usfirst.frc3824.HolonomicDrive.RobotMap;

/**
 *
 */
public class  TestOffsetRotation extends Command {
	double twist;
	
    public TestOffsetRotation() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        
        SmartDashboard.putNumber("twist value", 0.0);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	twist = SmartDashboard.getNumber("twist value");
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	RobotMap.driveTrainHolonomicDrive.mecanumDrive_Polar(0,0, twist);
    	SmartDashboard.putNumber("FL Motor", RobotMap.driveTrainLeftFront.get());
    	SmartDashboard.putNumber("FR Motor", RobotMap.driveTrainRightFront.get());
    	SmartDashboard.putNumber("BL Motor", RobotMap.driveTrainLeftRear.get());
    	SmartDashboard.putNumber("BR Motor", RobotMap.driveTrainRightRear.get());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
